language: node_js
node_js:
  - '6'

cache:
  directories:
    - node_modules

install: npm install

script: npm run lint && npm run build

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
